### ISSUE TITLE
使用新版本的driver时，使用默认参数创建ecs实例出错

### ISSUE THREAD

**Issue by orangedeng** [AliyunContainerService/docker-machine-driver-aliyunecs#15] opened 2016-12-25 15:59 UTC
命令上只使用了 ECS_ACCESS_KEY_ID ECS_ACCESS_KEY_SECRET ECS_SSH_PASSWORD，其他参数并未指定。

错误信息：
(testecs) testecs | Creating key pair for instance ...
(testecs) testecs | Configuring security groups instance ...
(testecs) testecs | Creating instance with image ubuntu1404_64_20G_aliaegis_20150325.vhd ...
Error creating machine: Error in driver during machine creation: testecs | Failed to create instance: Aliyun API Error: RequestId: FF7B42B8-B576-4C67-BA6A-4499C41B1B05 Status Code: 403 Code: OperationDenied Message: The resource is out of usage.

**Comment by denverdino** [comment] 2016-12-25 16:35
是当前地域的指定规格资源不足，请选择其他规格的ECS实例

**Comment by orangedeng** [comment] 2016-12-26 01:46
能否提供一个有可用资源的地域呢？我这边无论怎么尝试都无法创建出ECS实例了

**Comment by menglingwei** [comment] 2016-12-26 02:05
@orangedeng 可以在https://ecs-buy.aliyun.com/#/prepay 选定一个Region和规格

**Comment by denverdino** [comment] 2017-01-09 04:44
Pls try again and let us know if the problem is still there. I will close this issue now. Thanks

**Closed as completed by denverdino** 2017-01-09 04:44 UTC
